services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mlservice:
    build: ./ml-service
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=info     
      - NESTLE_CSV_PATH=/data/Nestle.csv
    volumes:
      - ./ml-service/data:/data

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8001/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10  
      start_period: 20s
    
    command: >
      sh -c "gunicorn -k uvicorn.workers.UvicornWorker --workers 3 --timeout 120 --bind 0.0.0.0:8001 --log-level info app.main:app"
    
    ports:
      - "8001:8001"


  worker:
    build:
      context: .        # <--- ESTO ES LO MÁS IMPORTANTE (apunta a la raíz)
      dockerfile: worker/Dockerfile
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - ./ml-service/app:/app/app
      - ./ml-service/scripts:/app/scripts

  dashboard:
    build: ./dashboard
    env_file: .env
    depends_on:
      mlservice:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
      - GUNICORN_CMD_ARGS="--log-level debug"
    command: >
      sh -c "gunicorn --workers 3 --timeout 120 --bind 0.0.0.0:8000 app.run:app"
         
    ports:
      - "8000:8000"

volumes:
  pgdata:


